### ISSUE TITLE
As a user I would like the console output to look nicer

### ISSUE THREAD

**Issue by everettraven** [everettraven/packageless#59]
Make the console output from the packageless tool look nicer by rendering markdown output using something like [charmbracelet/glamour](https://github.com/charmbracelet/glamour) and add a progress bar using something like [pterm/pterm](https://github.com/pterm/pterm)

**Comment by felixlevert** [comment]
I'd love to work on this!

**Comment by everettraven** [comment]
@felixlevert Sure thing! I would love to collaborate with you on this if you wouldn't mind (I could  break this into multiple issues for easier collaboration if needed)

**Comment by felixlevert** [comment]
That would be great! I'm open just let me know how you prefer to approach it.

**Comment by everettraven** [comment]
@felixlevert I will go ahead and split this issue into 2 different issues, one for implementing the progress bar and one for the markdown rendering.
